### Test the creation of a room
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
  "roomId": "R001",
  "number": "101",
  "building": "A",
  "campus": "Campus1"
}

### Test getting a room
GET http://localhost:3000/api/rooms/R001
Content-Type: application/json

### Test getting room info (excluding embeddings)
GET http://localhost:3000/api/rooms/R001/info
Content-Type: application/json


### Test getting room embeddings
GET http://localhost:3000/api/rooms/R001/embeddings
Content-Type: application/json


### Test getting room interventions
GET http://localhost:3000/api/rooms/R001/interventions
Content-Type: application/json

### Test updating a room
PUT http://localhost:3000/api/rooms/R001
Content-Type: application/json

{
  "roomId": "R001",
  "number": "102",
  "building": "B",
  "campus": "Polytech"
}


### Test deleting a room
DELETE http://localhost:3000/api/rooms/R001
Content-Type: application/json

### Test the creation of another room (used for intervention)
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
  "roomId": "R002",
  "number": "303",
  "building": "C",
  "campus": "Valrose"
}
